### PR TITLE
Merging in the good version

### PR DESCRIPTION
**Pull request by MithrilMania**
oO0 fixed most of the same issues I did, in a better way, and also added some neat features. Hoping oO0 will be the main fork now (since it is on the Play store) and I can contribute from here to there.

### CODE REVIEW

**Comment by oO0oO0oO0o0o00** [comment]
It's better that yours can be the main fork again, well, if you have some free time for it~

I don't quite like the fact that the kids are mainly using the app for cheating, I don't even know whether it's legal to allow this happening. I cannot just delete the cheating features or disable them for Worlds in survival mode, because it was not me that added the features.

**Comment by MithrilMania** [comment]
My last experience with Play Store wasn't great; so I'd prefer if you could publish, although I can still update. As for cheating, I'm not sure if any of that works for multiplayer (I only play single player anyway, where cheating really doesn't matter. With NBT editor you can do all sorts of interesting stuff). 

I'm having an issue getting it to compile at the moment; all of the "androidx" references are not found, and the build output is asking for "JetGradlePlugin". Is that something I need to install in Android Studio?

**Comment by oO0oO0oO0o0o00** [comment]
> My last experience with Play Store wasn't great; so I'd prefer if you could publish, although I can still update. As for cheating, I'm not sure if any of that works for multiplayer (I only play single player anyway, where cheating really doesn't matter. With NBT editor you can do all sorts of interesting stuff).
> 
> I'm having an issue getting it to compile at the moment; all of the "androidx" references are not found, and the build output is asking for "JetGradlePlugin". Is that something I need to install in Android Studio?

1. Since I don't know what happened to you with the Play Store, I'm not simply going to say "it is not that hard to use". Okay, I can help with publishing.
2. As for cheating, despite that it only works for local worlds, it still ruins experience. Maybe other people feel different, though. Anyway this does make me less willing to continue the development of the app.
3. You can first update your Android Studio to the latest, afterwards the support for `androidx` and other new features would (likely) come in automatically. If not, resolve all errors and warnings in Gradle files (project level & module level), sync with Gradle, and see. For problems, maybe you can try consult search engines and look for answers in places like StackOverflow. I don't remember seeing the word "JetGradlePlugin" before.
4. My support for chunk storage is again out-of-date and that's why I unpublished (not removed) the app. I've not look into the new format. Gamepedia and hex dump of a flat-world chunk may provide the hint.
5. The numeric id has long been replaced by string id, that's not much a problem as the list of id's can be easily found online. However, as the "val" (also called damage or special value or "data" in ModPE scripting `e.g. getData(x, y, z)`) that varies from 0 to 15 was also replaced by "states" which is far more complicated, the trouble comes in.
    1. It's rather hard to get an up-to-date list of all existing blocks. I tried programmatically generated all blocks with "val" 0 to 15 in an old format along with consecutive floating sands, rails and a mine cart. Then I opened the world in the new Minecraft, broke a sand to trigger the falling which would cause the chunk to be updated to newer format, then jump into the cart and set off to make nearby chunks being loaded and updated. That's pretty fun and I got a list of "known blocks", though not complete. Crawling through Gamepedia and parse the wiki-texts is also an idea, but the formats are not consistency enough for an automatic processing. I'm lazy for routine works so I never wished to do it manually. Minecraft should have the list itself in the apk, but I didn't find one. Some things are hard-coded perhaps. Not found at Gists or Twitters of Mojang staff, as well. (p.s. I also created Python script to generate the Java code that construct the list at run-time but I think I've lost it.)
    2. The current implementation of the app is not fully suitable for the "block state" thing and extensive rewriting is needed. I believe that it needs to be planned, and UML diagrams need to be drawn, in a "software engineering" manner which sounds not that fun.
6. I've also planned for a scripting support with which one can generate large structures that spans across lots of chunks that cannot be loaded in game at a same time, different from ModPE scripts. The similar feature was implemented years ago in a non-published app when I was in a (virtual) studio that create maps for Minecraft PE back then the target audience of the game is slightly older then those of today, but I wonder how many people are willing to use the feature and how many people have the ability to use it without messing up the game world. Maybe you/I can put a questionnaire in the app.

Good luck. Meow.

**Comment by oO0oO0oO0o0o00** [comment]
meow~

**Pull request merged**
